### ISSUE TITLE
Tera API key toh visible h

### ISSUE THREAD

**Issue by ADKR-26** [aalu-love/weather-app#1]
For Reference:
API Key:  ef530fc0919d4b27adc122308230307

Note: Teach me Something too

**Comment by aalu-love** [comment]
thik hai dekhte hai hide kise hide krte hai..but ye to normal html page hai.

Ek project Auth or Payment getaway, e-commerce bnnao

**Comment by ADKR-26** [comment]
link bhej
😊
Fir job dila dega na ??
